### ISSUE TITLE
Suggestion for button D

### ISSUE THREAD

**Issue by win2000se** [tlstommy/PiInk#1]
Button D would be good to use to clear the screen from ghosting

**Comment by tlstommy** [comment]
That's a good idea, although it may be better to do it automatically between image changes?

**Comment by win2000se** [comment]
Is that what it’s doing already? I assumed it wasn’t since the image
refreshes so much faster than with the inky scripts.

**Comment by tlstommy** [comment]
Technically yes, but the inky impression can still sometimes have ghosting issues. I just committed a new version with an added button in the WebUI to clear the screen!
