### ISSUE TITLE
No module named 'inky'

### ISSUE THREAD

**Issue by gigac280** [tlstommy/PiInk#15]
No process found using port 80!
starting PiInk frame webserver!
Traceback (most recent call last):
  File "/home/admin/e-Paper/RaspberryPi_JetsonNano/python/examples/PiInk/src/webserver.py", line 9, in <module>
    from inky.auto import auto
ModuleNotFoundError: No module named 'inky'

Server don't start, refused connection.

**Comment by tlstommy** [comment]
What board are you running on?

Ensure you have I2C and SPI enabled with `sudo raspi-config`. You can also manually install the inky library with `pip3 install inky[rpi,example-depends]`

Let me know if that works!

**Comment by gigac280** [comment]
Hi, thank's for fast reply!
Propably i see the problem - u need to add --break-system-packages to every Python package, if not - it doesn't install...

I tried to install all packages with this flag, but still see:

admin@piink:~/PiInk $ cat piink-log.txt
No process found using port 80!
starting PiInk frame webserver!
Traceback (most recent call last):
  File "/home/admin/PiInk/src/webserver.py", line 9, in <module>
    from inky.auto import auto
ModuleNotFoundError: No module named 'inky'

When i try to execute manual inky install i see:

__admin@piink:~/PiInk $ pip3 install inky[rpi,example-depends] --break-system-pack                                                                                                                                    ages
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: inky[example-depends,rpi] in /home/admin/.local/l                                                                                                                                    ib/python3.11/site-packages (1.5.0)
Requirement already satisfied: numpy in /home/admin/.local/lib/python3.11/site-p                                                                                                                                    ackages (from inky[example-depends,rpi]) (1.26.4)
Requirement already satisfied: smbus2 in /usr/lib/python3/dist-packages (from in                                                                                                                                    ky[example-depends,rpi]) (0.4.2)
Requirement already satisfied: spidev in /usr/lib/python3/dist-packages (from in                                                                                                                                    ky[example-depends,rpi]) (3.5)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from                                                                                                                                     inky[example-depends,rpi]) (2.28.1)
Requirement already satisfied: geocoder in /home/admin/.local/lib/python3.11/sit                                                                                                                                    e-packages (from inky[example-depends,rpi]) (1.38.1)
Requirement already satisfied: beautifulsoup4 in /home/admin/.local/lib/python3.                                                                                                                                    11/site-packages (from inky[example-depends,rpi]) (4.12.3)
Requirement already satisfied: font-fredoka-one in /home/admin/.local/lib/python                                                                                                                                    3.11/site-packages (from inky[example-depends,rpi]) (0.0.4)
Requirement already satisfied: font-source-serif-pro in /home/admin/.local/lib/p                                                                                                                                    ython3.11/site-packages (from inky[example-depends,rpi]) (0.0.1)
Requirement already satisfied: font-hanken-grotesk in /home/admin/.local/lib/pyt                                                                                                                                    hon3.11/site-packages (from inky[example-depends,rpi]) (0.0.2)
Requirement already satisfied: font-intuitive in /home/admin/.local/lib/python3.                                                                                                                                    11/site-packages (from inky[example-depends,rpi]) (0.0.4)
Requirement already satisfied: RPi.GPIO in /usr/lib/python3/dist-packages (from                                                                                                                                     inky[example-depends,rpi]) (0.7.1a4)
Requirement already satisfied: soupsieve>1.2 in /home/admin/.local/lib/python3.1                                                                                                                                    1/site-packages (from beautifulsoup4->inky[example-depends,rpi]) (2.5)
Requirement already satisfied: click in /home/admin/.local/lib/python3.11/site-p                                                                                                                                    ackages (from geocoder->inky[example-depends,rpi]) (8.1.7)
Requirement already satisfied: future in /home/admin/.local/lib/python3.11/site-                                                                                                                                    packages (from geocoder->inky[example-depends,rpi]) (1.0.0)
Requirement already satisfied: ratelim in /home/admin/.local/lib/python3.11/site                                                                                                                                    -packages (from geocoder->inky[example-depends,rpi]) (0.1.6)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from geoco                                                                                                                                    der->inky[example-depends,rpi]) (1.16.0)
Requirement already satisfied: decorator in /home/admin/.local/lib/python3.11/si                                                                                                                                    te-packages (from ratelim->geocoder->inky[example-depends,rpi]) (5.1.1)__

edit!
Board is Raspberry Pi 3b with Raspbian Lite 32bit.

**Comment by tlstommy** [comment]
Try and uninstall the inky package and then re run your install with that flag. 


Try and see if you can run the example files that Pimironi has for the Inky Impression too to ensure it's being detected by the pi.


I've been meaning to fix the install script so it's more reliable and should hopefully get around to it soon! 😅



I presume you are using a pimironi inky impression board right?

**Comment by gigac280** [comment]
After execute:
sudo pip install -r requirements.txt --break-system-packages
sudo pip3 install -r requirements.txt --break-system-packages

Now i see:
![image](https://github.com/tlstommy/PiInk/assets/169918325/b9ef6bb2-2d87-40df-8580-245e01cf8010)

After execute pip3 install numpy --break-system-packages:

Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (1.26.4)

I use Waveshare 7.5inch e-ink display with hat.

**Comment by tlstommy** [comment]
I haven't tested it with one of those so I'm not sure it will work, but it looks like something with numpy is causing the issue. Here is an issue thread opened in the inky repo that seems to be having a similar scenario https://github.com/pimoroni/inky/issues/190

**Comment by gigac280** [comment]
Finallly i propably installed all the python packages, but now... 

No process found using port 80!
starting PiInk frame webserver!
usage: webserver.py [-h] [--simulate] --type
                    {what,phat,phatssd1608,impressions,7colour,whatssd1683,impressions73}
                    [--colour {red,black,yellow}]
webserver.py: error: the following arguments are required: --type/-t
/home/admin/PiInk
{'jpg', 'jpeg', 'webp', 'png'}
Failed to detect an Inky board. Trying --type/--colour arguments instead...

Is Piink support Waveshare 2 colour 7.5inch display? :D

**Comment by tlstommy** [comment]
currently piink only supports Pimironi Inky Impressions
