### ISSUE TITLE
Inky Modules not being installed

### ISSUE THREAD

**Issue by mbasaly** [tlstommy/PiInk#18]
![Screenshot (29)](https://github.com/user-attachments/assets/f3848f02-de2c-4b5b-8b97-81dc89858bc2)

Hi there, I have been trying to install the packages per your instructions but I keep getting errors about this installer trying to install inky outside a virtual environment (if I understand correctly). I have tried to install Inky separately to see if it helps but that does not seem to work. Am I missing something in how I should be running this process?

**Comment by mbasaly** [comment]
Sorry just to clarify what happens after this point - PiInk says install was successful, but then the webserver does not stay started due to the module not being found (presumably because it's not getting installed at this step)
![image](https://github.com/user-attachments/assets/48d63a50-4daa-4e11-8b6f-b6d3586904d5)

**Comment by tlstommy** [comment]
Yeah, I need to fix the install script to work for virtual environments. Try this
```
git clone https://github.com/pimoroni/inky
cd inky
./install.sh
``` 
or setting up in a venv

**Comment by mbasaly** [comment]
Thanks for your response :) 
I couldn't get it working with a venv but in the end realised you can force pip to allow these kinds of installs even from within an install script. I ran  `python3 -m pip config debug ` to find the location of my pip.conf file, and added `break-system-packages = true` which allows pip installs to work outside a venv. All good now!
