### ISSUE TITLE
cURL command

### ISSUE THREAD

**Issue by ChopsKingsland** [tlstommy/PiInk#3]
Is there an example cURL command to upload an image to the display, as I can’t seem to reverse engineer the form?

**Comment by tlstommy** [comment]
Hi, thanks for raising this issue!

I just pushed a new commit, 151639cdd62dc2cce8fa473088ed846f85593ac3 to enable cURL command uploading to the frame. 

Here is the command I used to upload images: `curl -X POST -F "file=@image.png" piink.local`

please let me know if that solves your issue!

**Comment by ChopsKingsland** [comment]
Yep, that works - thanks! 

It didn't work until I removed the quotes around the file part, so it reads `curl -X POST -F file=@image.png piink.local`

The cURL command also returned a 400, although the image still displayed on the e-ink. Could it return a 200 instead?
```html
<!doctype html>
<html lang=en>
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
```

Now I just need to work out how to send a file from iOS shortcuts so I can share directly from the photos app

**Comment by tlstommy** [comment]
ok thanks! ill get to work on returning the correct code!

**Comment by ChopsKingsland** [comment]
I made a working iOS Shortcut, so I can share to PiInk directly from Photos:

[https://www.icloud.com/shortcuts/7f373666b35044649534a8bbb99db116](https://www.icloud.com/shortcuts/7f373666b35044649534a8bbb99db116)

edit: resizing to width is the best for images that are the wrong size, to stop black bars and stretching when showing on PiInk

**Comment by tlstommy** [comment]
Should now be returning proper codes with the latest commit!
